config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users
resources :events
resources :videos
resources :documents, path: 'virtus', as: 'virtus', only: [:index, :new, :create, :destroy]
  


# Home/Root Route
  root to: 'members#index'

  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale

  # Get Requests
  get '/calendar', to: 'events#calendar'
  get '/contact', to: 'members#contact'
  get '/about', to: 'members#about'
  get '/', to: 'members#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  # get '/users/:id', to: 'members#index'
  # get '/virtus', to: 'members#virtus'
  # get '/documents/show', to: 'documents#show', as: :show_document
  get '/lectura-del-dia', to: 'scraping#lectura'
  get '/daily-gospel', to: 'scraping#daily_gospel'

  get '/noticias', to: 'scraping#weekly_bulletin'
  get '/pdfs/formulario.pdf', to: redirect('/pdfs/formulario.pdf')
  get '/videos/search', to: 'videos#index', as: 'search_videos'
  get '/events/search', to: 'events#index', as: 'search_events'

  get '/signup', to: 'sessions#signup'
  post '/signup', to: 'sessions#create_user'


# Uncomment this when working with these paths
  get '/angeles-de-dios', to: 'members#angeles'
  get '/luz-del-mundo', to: 'members#luz'
  get '/misa', to: 'members#misa'
  get '/resos', to: 'members#resos'
  get '/forms', to: 'members#forms'
  get '/our-parish', to: 'members#about_parish'
  get '/stkilian-new-member', to: 'members#stkilian_new_member'
  get '/pastoral-familiar', to: 'members#pastoral_familiar'
  get '/spanish-weekly-bulletin', to: 'members#spanish_weekly_bulletin'
  get '/guadalupano', to: 'members#guadalupano'
  get '/copyright', to: 'members#copyright'
  get '/about-the-bishop', to: 'members#bishop'






  # This will be partials instead and will render on various pages
  # get '/guadalupanos', to: 'members#guadalupanos'
 


  # Post Requests
  post '/login', to: 'sessions#create'
  post '/events/new', to: 'events#create'

  # Delete Requests
  delete '/logout', to: 'sessions#destroy'
end

app/views/partials/_aboutPriest.html.erb
<!-- About Padre Romulo -->
<div class="author-section" id="about-the-priest">
  <div class="container">
    <div class="row">
      <div class="col-md-5 d-flex align-items-center justify-content-center">
        <%= image_tag 'profile/romulo.png', class: "rounded-circle", alt:"Padre Romulo"%>
      </div>
      <div class="col-md-7">
        <h2><%= t('romulo.heading1') %></h2>
        <h5><%= t('romulo.heading2') %></h5>
        <p><%= t('romulo.p1') %></p>
        <p><%= t('romulo.p2') %></p>
        <p><%= t('romulo.p3') %></p>
        <p><%= t('romulo.p4') %></p>
        <p><%= t('romulo.p5') %></p>
        <p><%= t('romulo.p6') %></p>
      </div>
    </div>
  </div>
  </div>

app/views/partials/_bodas.html.erb
<!-- <%= render "/partials/placeholder" %> -->


<section id="bodas">
    <div class="jumbotron text-center">
    <h1 class="display-4 text-center"><%= t('bodas-heading') %></h1>
        <%= t('bodas-body').html_safe %>
      <%= image_tag 'noticias/quince2.png', class: "quince-image" %>

        <hr class="my-4">
       
      </div>
</section>

app/views/partials/_carousel.html.erb
<!-- Carousel items with bible verses -->
<section id="carousel">
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="4" aria-label="Slide 5"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="5" aria-label="Slide 6"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="6" aria-label="Slide 7"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="7" aria-label="Slide 8"></button>
      </div>

      <div id="bible">
        <%= image_tag "bible.png", class:"bible", width: "100"%>
    </div>
      <div class="carousel-inner container-fluid compTextBox">
        
        <div class="carousel-item active">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v1-content') %></h5>
            <p><%= t('v1-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v2-content') %></h5>
            <p><%= t('v2-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v3-content') %></h5>
            <p><%= t('v3-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v4-content') %></h5>
            <p><%= t('v4-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v5-content') %></h5>
            <p><%= t('v5-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v6-content') %></h5>
            <p><%= t('v6-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v7-content') %></h5>
            <p><%= t('v7-verse') %></p>
          </div>
        </div>
  
        <div class="carousel-item">
          <div class="carousel-caption d-none d-md-block">
            <h5><%= t('v8-content') %></h5>
            <p><%= t('v8-verse') %></p>
          </div>
        </div>
  
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </section>
  

app/views/partials/_features.html.erb
<section id="features">
    <div class="feature">
      <div>
        <h6 class="investPeople"><%= t('features-main-title') %></h6>
        <h2 class="betterEducation"><%= t('features-subtitle').html_safe %></h2>
        <p class="featureSubtitle"><%= t('features-caption') %></p>
      
    
    </div>
      <div class="row featuresTogether featTogeth">
        
        <div class="feature-box col-lg-4" id="ind-card">
          <%= image_tag 'innovation/teen.png', class: "innovation-image", alt:"teen", width:"180px"%>
          <h4 class="feature-title"><%= t('feature-title1') %></h4>
          <p class="features-text"><%= t('feature-context1') %></p>
        </div>
        <div class="feature-box col-lg-4" id="ind-card">
          <%= image_tag 'innovation/light.png', class: "innovation-image", alt:"lightbulb", width:"150px"%>
          <h4 class="feature-title"><%= t('feature-title2') %></h4>
          <p class="features-text"><%= t('feature-context2') %></p>
        </div>
        <div class="feature-box col-lg-4" id="ind-card">
          <%= image_tag 'innovation/team.png', class: "innovation-image", alt:"team", width:"150px"%>
          <h4 class="feature-title"><%= t('feature-title3') %></h4>
          <p class="features-text"><%= t('feature-context3') %></p>
        </div>
      </div>
    </div>
  </section>

app/views/partials/_flash.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="text-center">
                <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
                    <strong><%= msg %></strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    </button> 
                </div>
            </div>
    <% end %>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <div class="container-fluid">
  <div class="row footer-section" id="">
    <div class="card col-lg-3 col-md-6 col-sm-12" id="ind-div-footer">
      <div class="card-body footerLogoDiv">
      <a class="" style="font-size: 20px; margin-top: 0;" href="/" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/'; }, 100);"><%= t('footer-sdj-link') %></a>
      <%= image_tag "logowhitedove.jpg", class: "", style: "width: 70px; margin: 0 auto;" %>
      <!-- <a href="/" class="btn-primary">Home</a> -->
      <a href="/about" class="btn-primary">About</a>
    </div>
    </div>

    <div class="card col-lg-3 col-md-6 col-sm-12" id="ind-div-footer">
      <div class="card-body footerCard">
      <a href="/<%= t('gospel-link-footer') %>" class="btn-primary"><%= t('footer-gospel-spanish') %></a>
      <a href="/noticias" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/noticias'; }, 100);"><%= t('footer-noticias') %></a>
      <a href="/virtus" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/virtus'; }, 100);">VIRTUS</a>
      <a href="/videos?page=1" class="btn-primary">Videos</a>
      <!-- <a href="#" class="btn-primary">Blog</a> -->
    </div>

    </div>

    <div class="card col-lg-3 col-md-6 col-sm-12" id="ind-div-footer">
      <div class="card-body footerCard">
      <a href="/events" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/events'; }, 100);"><%= t('footer-events') %></a>
      <a href="/calendar" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/calendar'; }, 100);">Calendar</a>
      <a href="/forms" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/forms'; }, 100);"><%= t('footer-resources') %></a>
      <a href="/our-parish" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/our-parish'; }, 100);"><%= t('nuestra-parroquia') %></a>

    </div>
    </div>

    <div class="card col-lg-3 col-md-6 col-sm-12" id="ind-div-footer">
      <div class="card-body footerCard">
      <a href="/contact" class="btn-primary" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/contact'; }, 100);"><%= t('footer-contact') %></a>
      <p class="address">485 Conklin Street</p>
      <p class="address">Farmingdale, New York 11735</p>
      <p class="address">(516) 249-0127</p>
    </div>
    </div>
  </div>

  <div class="text-center p-4 copyright" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="/copyright" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/copyright'; }, 100);"><%= t('footer-sdj-link') %></a>
  </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="App-header">
    <div class="card" id="header">
      <%= image_tag "group.jpg", id: "first-image"%> 
      <%= image_tag "elmer.jpg", id: "second-image"%>
      <%= image_tag "fermina.jpg", id: "third-image"%> 
      <%= image_tag "john.jpg", id: "fourth-image"%> 
      <%= image_tag "jeffrey.jpg", id: "fifth-image"%> 
      <%= image_tag "joseph.jpg", id: "sixth-image"%> 

      <!-- <div class="first-image"></div>
      <div class="second-image"></div>
      <div class="third-image"></div>
      <div class="fourth-image"></div>
      <div class="fifth-image"></div>
      <div class="sixth-image"></div> -->


  
      <div class="card-body" id="header-body">
        <p class="card-text text-center" id="header-group-two"><%= t('header-group-two') %></p>
        <h5 class="card-title text-center" id="header-welcome">

          <% if !current_user %>
          <%= t('header-welcome') %>
          <% else %>
          <%= t('header-welcome-with-first-and-last', first_name: current_user.first_name, last_name: current_user.last_name) %>
          <% end %>
        
        </h5>
        <p class="card-text text-center" id="header-group"><%= t('header-group') %> </p>
      </div>
    </div>
  </header>

  <!-- No need for header tag, may be able to remove it -->

app/views/partials/_jovenes.html.erb
<div class="mainDiv">
  <div class="jovenesPartialMedia">
    <div class="media-body">
      <div class="cVHeading">
        <h6 class="investPeople"><%= t('youth-group') %></h6>
        <%= t('jpartial-header').html_safe %>
        <p><%= t('jovenes-partial-context') %></p>
        <p><%= t('jovenes-partial-slogan') %></p>
      </div>

      <div class="jovenesPartialInfo float-child">
        <h4><%= t('jpartial-h1') %></h4>
        <p><%= t('jpartial-p1') %></p>

        <h4><%= t('jpartial-h2') %></h4>
        <p><%= t('jpartial-p2') %></p>

        <h4><%= t('jpartial-h3') %></h4>
        <p><%= t('jpartial-p3') %></p>

        <h4><%= t('jpartial-h4') %></h4>
        <p><%= t('jpartial-p4') %></p>

        <a href="/angeles-de-dios" class="btn btn-primary btn-lg"
          ><%= t('quieres-ver-mas-button') %></a
        >
      </div>

      <div
        class="float-child second-jovenes-div d-flex align-items-center justify-content-center"
        id="second-jovenes-div"
      >
        <!-- <span class="media-left">
            <iframe
              width="500"
              height="315"
              src="https://www.youtube.com/embed/mZF9ZkHE80U"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowfullscreen
            ></iframe>
          </span> -->

        <div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
          <!-- Slides -->
          <div class="carousel-inner">
            <div class="carousel-item active" style="height: 500px">
              <%= image_tag 'jovenes/1.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/2.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/3.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/4.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/5.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/6.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/7.jpg', class: "d-block w-100" %>
            </div>

            <div class="carousel-item" style="height: 500px">
              <%= image_tag 'jovenes/8.jpg', class: "d-block w-100" %>
            </div>
          </div>

          <!-- Controls -->
          <a
            class="carousel-control-prev"
            href="#imageCarousel"
            role="button"
            data-bs-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#imageCarousel"
            role="button"
            data-bs-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-xl" id="navbar">
  <div class="container-fluid inside-navbar">
    <span><%= image_tag "logowhitedove.jpg", class: "logo" %></span
    ><a id="brand-name-right-corner" class="navbar-brand" href="/" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/'; }, 100);"><%= t('brand-name-right-corner') %></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarNavDropdown"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/'; }, 100);">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/events" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/events'; }, 100);"><%= t('events') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/videos?page=1" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/videos?page=1'; }, 100);">Videos</a>
        </li>
        




        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t('grupos') %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="min-width: 250px; text-align: center">
            <li class="dropdown-item"><a href="/misa" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/misa'; }, 100);"><%= t('groups.misas') %></a></li>
            <li class="dropdown-item"><a href="/virtus" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/virtus'; }, 100);">VIRTUS</a></li>
            <li class="dropdown-item"><a href="/resos" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/resos'; }, 100);"><%= t('groups.rosary') %></a></li>
            <li class="dropdown-item"><a href="/guadalupano" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/guadalupano'; }, 100);"><%= t('groups.guadal') %></a></li>
            <li class="dropdown-item"><a href="/luz-del-mundo" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/luz-del-mundo'; }, 100);"><%= t('groups.luz') %></a></li>
            <li class="dropdown-item"><a href="/angeles-de-dios" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/angeles-de-dios'; }, 100);"><%= t('groups.angeles') %></a></li>
            <li class="dropdown-item"><a href="/pastoral-familiar" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/pastoral-familiar'; }, 100);"><%= t('groups.pastoral') %></a></li>
            <li class="dropdown-item"><a href="/our-parish" style="color: black" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/our-parish'; }, 100);"><%= t('groups.parish') %></a></li>
          </ul>
        </li>




        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t('idioma') %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "🇺🇸 English", switch_locale_path(:en), class: "dropdown-item", style: "color: black", onclick: "event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/switch_locale/en'; }, 100);"  %>
            <%= link_to "🇪🇸 Español", switch_locale_path(:es), class: "dropdown-item", style: "color: black", onclick: "event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/switch_locale/es'; }, 100);" %>
          </ul>
        </li>
       





        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hi, <%= current_user.first_name %> 
              <% if current_user.avatar.attached? %>
                <%= image_tag(current_user.avatar, width: '30px', class: 'rounded-circle topPic', style: "") %>
              <% else %>
                <%= image_tag("profileExample.jpeg", width: '30px', class: 'rounded-circle topPic', style: "") %>
              <% end %>
            </a>


            <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="min-width: 250px; text-align: center">
              <li class="dropdown-item"><a href="<%= user_path(current_user) %>" style="color: black;" onclick="event.preventDefault(); setTimeout(function() { location.reload(true)} , 100); setTimeout(function() { window.location.href = '/users/<%= current_user.id %>'; }, 100); ">View Profile</a></li>
              <li class="dropdown-item"><a href="<%= edit_user_path(current_user) %>" style="color: black;" onclick="event.preventDefault(); setTimeout(function() { location.reload(true)} , 100); setTimeout(function() { window.location.href = '/users/<%= current_user.id %>/edit'; }, 100); ">Edit Profile</a></li>
              <li class="dropdown-item"><a href="/logout" style="color: black" onclick="event.preventDefault(); if (confirm('Are you sure you want to proceed?')) { setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/logout'; }, 100); }">Log Out</a></li>
            </ul>
          </li>

        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/login" onclick="event.preventDefault(); setTimeout(function() { location.reload(true); }, 100); setTimeout(function() { window.location.href = '/login'; }, 100);">Log In</a>
          </li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/partials/_pastoral_staff.html.erb
<section id="" style="padding-bottom: 50px; background: #e6f0fe">
    <div class="events-heading">
      <h2 id="videos-heading" class="">Ven a Conocer el Staff Pastoral!</h2>
    </div>
  
    <div class="container">
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'avatars/john-ryan-avatar.png', class: "rounded-circle", alt:"Image of John Ryan", width:"150px"%>
          <h5 class="profile-pic">John Ryan</h5>
          <h6>Business & Facility Manager</h6>
          <h6><a href="mailto:johnr@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
  
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'avatars/pastor-avatar.png', class: "rounded-circle",
          alt:"", width:"150px"%>
          <h5 class="profile-pic">Monsignor Mark Rowen</h5>
          <h6>Pastor de la Parroquia St.Kilian</h6>
          <h6><a href="mailto:pastor@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
  
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'profileExample.jpg', class: "rounded-circle",
          alt:"", width:"150px"%>
          <h5 class="profile-pic">Mrs. Christina Dunbar</h5>
          <h6>Bookkeeper & Safe Environment Coordinador</h6>
          <h6><a href="mailto:christinad@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
  
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'avatars/jeana-lewis-avatar.png', class: "rounded-circle",
          alt:"", width:"150px"%>
          <h5 class="profile-pic">Mrs. Jeana Lewis</h5>
          <h6>Outreach Director & Bulletins</h6>
          <h6><a href="mailto:jeanal@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
  
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'profileExample.jpg', class: "rounded-circle",
          alt:"", width:"150px"%>
          <h5 class="profile-pic">Mrs. Jennifer Miller</h5>
          <h6>Parish Secretary</h6>
          <h6><a href="jenniferm@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
  
        <div class="col-lg-4 col-md-6 text-center mb-4">
          <%= image_tag 'profileExample.jpg', class: "rounded-circle",
          alt:"", width:"150px"%>
          <h5 class="profile-pic">Mrs. Jane Zollo</h5>
          <h6>Stewardship Director & Website</h6>
          <h6><a href="janezr@stkilian.com" style="text-decoration: none;">Send Email</a></h6>
        </div>
      </div>
    </div>
  </section>
  

app/views/partials/_resos.html.erb
<section id="rosarySection">
<div class="container mt-4">
    <div class="row rosary-section text-center">
        <div class="col-md-6 text-center">
            <img src="https://seguidoresdejesus.s3.amazonaws.com/rosary.png" class="img-fluid" alt="Imagen del Rosario">
        </div>
        <div class="col-md-6 rosary-section-content">
            <h2 class="display-4"><%= t('resos-partial-heading') %></h2>
            <%= t('resos-partial-ptags').html_safe%>
            <a href="/resos" class="btn btn-primary btn-lg"><%= t('quieres-aprender-mas-button') %></a>
        </div>
    </div>
</div>
</section>