config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users
resources :events
resources :videos
resources :documents, path: 'virtus', as: 'virtus', only: [:index, :new, :create, :destroy]
  


# Home/Root Route
  root to: 'members#index'

  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale

  # Get Requests
  get '/calendar', to: 'events#calendar'
  get '/contact', to: 'members#contact'
  get '/about', to: 'members#about'
  get '/', to: 'members#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  # get '/users/:id', to: 'members#index'
  # get '/virtus', to: 'members#virtus'
  # get '/documents/show', to: 'documents#show', as: :show_document
  get '/lectura-del-dia', to: 'scraping#lectura'
  get '/daily-gospel', to: 'scraping#daily_gospel'

  get '/noticias', to: 'scraping#weekly_bulletin'
  get '/pdfs/formulario.pdf', to: redirect('/pdfs/formulario.pdf')
  get '/videos/search', to: 'videos#index', as: 'search_videos'
  get '/events/search', to: 'events#index', as: 'search_events'

  get '/signup', to: 'sessions#signup'
  post '/signup', to: 'sessions#create_user'


# Uncomment this when working with these paths
  get '/angeles-de-dios', to: 'members#angeles'
  get '/luz-del-mundo', to: 'members#luz'
  get '/misa', to: 'members#misa'
  get '/resos', to: 'members#resos'
  get '/forms', to: 'members#forms'
  get '/our-parish', to: 'members#about_parish'
  get '/stkilian-new-member', to: 'members#stkilian_new_member'
  get '/pastoral-familiar', to: 'members#pastoral_familiar'
  get '/spanish-weekly-bulletin', to: 'members#spanish_weekly_bulletin'
  get '/guadalupano', to: 'members#guadalupano'
  get '/copyright', to: 'members#copyright'
  get '/about-the-bishop', to: 'members#bishop'






  # This will be partials instead and will render on various pages
  # get '/guadalupanos', to: 'members#guadalupanos'
 


  # Post Requests
  post '/login', to: 'sessions#create'
  post '/events/new', to: 'events#create'

  # Delete Requests
  delete '/logout', to: 'sessions#destroy'
end

app/models/video.rb
class Video < ApplicationRecord


    validates :name, presence: {message: "can't be empty"}
    validates :link_to_video, presence: {message: "can't be empty"}
    validates :date_created, presence: {message: "can't be empty"}
    validates :category, presence: {message: "can't be empty"}

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_action :require_login, only: [:new, :edit, :update, :destroy]


    # def index
    #     videos_per_page = 6
    #     page = params[:page].to_i || 2
    #     offset = [(page - 1) * videos_per_page, 0].max
      
    #     if params[:search].present? || params[:category].present?
    #       category = params[:category]
    #       total_videos = Video.where('lower(name) LIKE ?', "%#{params[:search].downcase}%").count
    #       @videos = Video.where('lower(name) LIKE ?', "%#{params[:search].downcase}%").order(date_created: :desc).offset(offset).limit(videos_per_page) if params[:search].present?
    #       @videos = Video.where(category: category) if params[:category].present?
    #     else
    #       total_videos = Video.count
    #       @videos = Video.all.order(date_created: :desc).offset(offset).limit(videos_per_page)
    #     end
      
    #     @total_pages = (total_videos.to_f / videos_per_page).ceil
    #   end

    def index
        videos_per_page = 6
        page = params[:page].to_i || 2
        offset = [(page - 1) * videos_per_page, 0].max
      
        if params[:search].present? || params[:category].present?
          query = "%#{params[:search].downcase}%"
          category = params[:category]
    
          videos = Video.all
          videos = videos.where('lower(name) LIKE ?', query) if params[:search].present?
          videos = videos.where(category: category) if params[:category].present?
    
          total_videos = videos.count
          @videos = videos.order(date_created: :desc).offset(offset).limit(videos_per_page)
        else
          total_videos = Video.count
          @videos = Video.all.order(date_created: :desc).offset(offset).limit(videos_per_page)
        end
      
        @total_pages = (total_videos.to_f / videos_per_page).ceil
      end
      

    def new
        @video = Video.new
    end

    def edit
        @video = Video.find_by(id: params[:id])
    end

    def update
        @video = Video.find_by(id: params[:id])
        if @video.update(video_params)
            redirect_to '/videos?page=1', success: "Video editado con éxito"
        else
            redirect_to new_video_path, danger: "El video NO se edito con éxito"
        end
    end

    def create
        @video = Video.new(video_params)
        if @video.save
            redirect_to '/videos?page=1', success: "Video añadido con éxito"
        else
            redirect_to new_video_path, danger: "El video NO se agregó con éxito"
        end
    end

    def destroy
        @video = Video.find_by(id: params[:id])
        @video.destroy
        redirect_to videos_path, success: "El Video se ah eliminado con exito."
    end

    
    private

    def video_params
        params.require(:video).permit(:name, :link_to_video, :date_created, :category)
    end
    


    
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/videos/edit.html.erb
    <div class="container-fluid newCourseForm">
      <h3 class="welcomeBack" style="text-align: center;"><%= t('editar-video-heading') %></h3>

      <%= form_for @video, url: video_path do |f| %>
      <%= hidden_field_tag :page, params[:page] || 1  %>
        <div class="mb-3">
          <%= f.label :name, 'Nombre del Video', class: "form-label" %>
          <%=f.text_field :name, class: "form-control Input", :placeholder => 'Ingrese Nombre del Video', value: f.object.name %>
        </div>

        <div class="mb-3">
            <%= f.label :link_to_video, 'URL del Video', class: "form-label" %>
            <%=f.text_field :link_to_video, class: "form-control Input", :placeholder => 'Ingrese URL del Video', value: f.object.link_to_video%>
          </div>

        <div class="mb-3">
            <%= f.label :date_created, 'Fecha del Video', class: "form-label" %>
            <%=f.date_field :date_created, class: "form-control Input", :placeholder => 'Ingrese Fecha del Video', value: f.object.date_created  %>
        </div>

        <div class="mb-3">
          <%= f.label :category, 'Categoría del Video', class: "form-label" %>
          <%= f.select :category, ['Predicas', 'Juvenil', 'Musica', 'Dramas', 'Testimonios', 'Inspiracion', 'Retiro/Vigilia', 'Podcast'], { prompt: 'Seleccione una categoría' }, class: "form-control Input" %>
        </div>
      
        <%=f.submit t('edit-video-button'), class: "btn btn-lg btn-default loginButton" %> 
      <%end%>

    </div>
  

app/views/videos/index.html.erb
<section id="events">
    <div class="events-heading">
      <h2 id="videos-heading" class="text-white"><%= t('ven-y-goza') %></h2>
      <% if current_user %>
      <%= link_to 'Add New Video', new_video_path, class: "btn btn-primary"%>
      <% end %>
    </div>


    



  
  <div id="videos-section">
  
      
    <% if !@videos.blank? %>

    <%= form_tag videos_path, method: :get, id: 'search-form' do %>
    <%= hidden_field_tag :page, params[:page] %>
  <div class="row">
    <div class="col-md-11">
      <%= text_field_tag :search, params[:search], placeholder: 'Search videos', class: "form-control" %>
    </div>
<br><br>
    <div class="col-md-11">
      <%= select_tag :category, options_for_select(['Predicas', 'Juvenil', 'Musica', 'Dramas', 'Testimonios', 'Inspiracion', 'Retiro/Vigilia', 'Podcast'], params[:category]), prompt: 'All Categories', class: "form-control" %>
    </div>

    <div class="col-md-1">
      <%= submit_tag 'Search', class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>
  
    <div class="row">
      <% @videos.map do |video| %>
      <div class="col-xl-4 col-lg-6" >
        <div id="video">
          <h4 class="text-white text-center"><%= video.name %></h4>
          <iframe
            src="<%= video.link_to_video %>"
            allowFullScreen
            title="<%= video.name %>"
          ></iframe>
          <figcaption class="text-white">

            <% if current_user %>
            <%= link_to 'Delete Video', video_path(video), method: :delete, data: { confirm: 'Are you sure you want to delete the video?' }, class: "text-white delete-video" %>
            <%= link_to "Editar Video", edit_video_path(video), class: "text-white delete-video" %>
            <% end %>
            <%= video.date_created.strftime("%B %d, %Y") %>
        
          </figcaption>
        </div>
      </div>
      <% end %>


      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          <% if params[:page].to_i > 1 %>
            <li class="page-item">
              <%= link_to 'Previous', videos_path(page: params[:page].to_i - 1), class: 'btn btn-primary' %>
            </li>
          <% end %>
      
          <% if params[:page].to_i < @total_pages %>
            <li class="page-item">
              <%= link_to 'Next', videos_path(page: params[:page].to_i + 1), class: 'btn btn-primary' %>
            </li>
          <% end %>
        </ul>
      </nav>


    </div>
  
    <% else %>
  
    <div class="events-heading">
      <h2 id="videos-heading" class="text-white">No hay videos en este momento</h2>
    </div>
  
    <% end %>
  </div>


  

  </section>
  <%= render "/partials/invitamos"%>

app/views/videos/new.html.erb
<!-- <div class="section textInputs"> -->
    <div class="container-fluid newCourseForm">
      <h3 class="welcomeBack" style="text-align: center;"><%= t('new-video-heading') %></h3>



      <%= form_for :video, url: videos_path do |f| %>
      <%= hidden_field_tag :page, params[:page] || 1  %>
        <div class="mb-3">
          <%= f.label :name, t('label-video-name'), class: "form-label" %>
          <%=f.text_field :name, class: "form-control Input", :placeholder => t('place-name-video') %>
        </div>

        <div class="mb-3">
            <%= f.label :link_to_video, t('label-link-video'), class: "form-label" %>
            <%=f.text_field :link_to_video, class: "form-control Input", :placeholder => t('place-url-video') %>
          </div>

        <div class="mb-3">
            <%= f.label :date_created, t('label-date-created'), class: "form-label" %>
            <%=f.date_field :date_created, class: "form-control Input"%>
        </div>

        <div class="mb-3">
          <%= f.label :category, t('label-category'), class: "form-label" %>
          <%= f.select :category, ['Predicas', 'Juvenil', 'Musica', 'Dramas', 'Testimonios', 'Inspiracion', 'Retiro/Vigilia', 'Podcast'], { prompt: t('place-category-video') }, class: "form-control Input" %>
        </div>
      
        <%=f.submit t('new-video-button'), class: "btn btn-lg btn-default loginButton" %> 
      <%end%>


      

    </div>
  <!-- </div> -->
  