config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :users
resources :events
resources :videos
resources :documents, path: 'virtus', as: 'virtus', only: [:index, :new, :create, :destroy]
  


# Home/Root Route
  root to: 'members#index'

  get 'switch_locale/:locale', to: 'application#switch_locale', as: :switch_locale

  # Get Requests
  get '/calendar', to: 'events#calendar'
  get '/contact', to: 'members#contact'
  get '/about', to: 'members#about'
  get '/', to: 'members#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  # get '/users/:id', to: 'members#index'
  # get '/virtus', to: 'members#virtus'
  # get '/documents/show', to: 'documents#show', as: :show_document
  get '/lectura-del-dia', to: 'scraping#lectura'
  get '/daily-gospel', to: 'scraping#daily_gospel'

  get '/noticias', to: 'scraping#weekly_bulletin'
  get '/pdfs/formulario.pdf', to: redirect('/pdfs/formulario.pdf')
  get '/videos/search', to: 'videos#index', as: 'search_videos'
  get '/events/search', to: 'events#index', as: 'search_events'

  get '/signup', to: 'sessions#signup'
  post '/signup', to: 'sessions#create_user'


# Uncomment this when working with these paths
  get '/angeles-de-dios', to: 'members#angeles'
  get '/luz-del-mundo', to: 'members#luz'
  get '/misa', to: 'members#misa'
  get '/resos', to: 'members#resos'
  get '/forms', to: 'members#forms'
  get '/our-parish', to: 'members#about_parish'
  get '/stkilian-new-member', to: 'members#stkilian_new_member'
  get '/pastoral-familiar', to: 'members#pastoral_familiar'
  get '/spanish-weekly-bulletin', to: 'members#spanish_weekly_bulletin'
  get '/guadalupano', to: 'members#guadalupano'
  get '/copyright', to: 'members#copyright'
  get '/about-the-bishop', to: 'members#bishop'






  # This will be partials instead and will render on various pages
  # get '/guadalupanos', to: 'members#guadalupanos'
 


  # Post Requests
  post '/login', to: 'sessions#create'
  post '/events/new', to: 'events#create'

  # Delete Requests
  delete '/logout', to: 'sessions#destroy'
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :file
  

  validate :validate_file_and_language_presence
  validates :language, presence: true


  private

  def validate_file_and_language_presence
    unless file.attached? && language.present?
      errors.add(:base, "File and language must be present")
    end
  end

end

app/controllers/documents_controller.rb
# app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_login, only: [:new, :edit, :update, :destroy]

  def index 
    @english_document = Document.where(language: 'en').first
    @spanish_document = Document.where(language: 'es').first
    response.headers.delete('Content-Disposition')
  end

  def new
    @english_document = Document.new
    @spanish_document = Document.new
  end


def create
  # Check if the English form was submitted
  if params[:document][:language] == 'en'
    @english_document = Document.new(document_params)
    @english_document.language = 'en' # Set the language to English

    if @english_document.save
      redirect_to virtus_path, success: 'English Document was successfully created.'
    else
      render :new, danger: "English Document was NOT SAVED"
    end
  # Check if the Spanish form was submitted
  elsif params[:document][:language] == 'es'
    @spanish_document = Document.new(document_params)
    @spanish_document.language = 'es' # Set the language to Spanish

    if @spanish_document.save
      redirect_to virtus_path, success: 'Spanish Document was successfully created.'
    else
      render :new, danger: "Spanish Document was NOT SAVED"
    end
  else
    # If no form was submitted or the language was not specified, redirect to the appropriate page
    redirect_to virtus_path, alert: 'No valid form was submitted.'
  end
end


  def destroy
    @document = Document.find(params[:id])
    @document.file.purge if @document.file.attached?
    @document.destroy
    redirect_to virtus_path, success: 'Document was successfully deleted.'
  end

  private

  def document_params
    params.require(:document).permit(:file, :language)
  end
end

app/views/documents/index.html.erb
<section id="about-author" class="bg-light py-5">
  <h2 class="text-center h2Virtus">
    <%= t('h2Virtus-title') %>
  </h2>

  <div class="container text-center">
    <div class="row">
      <div class="col-md-4 virtusLogoDiv">
        <%= image_tag 'virtus/virtusLogo.png', class: "virtusLogo", alt:"virtusLogo"%>
      </div>
      <div class="col-md-8 p-4 virtusContext">
        <h2><%= t('h2Virtus-subtitle') %></h2>
        <p>
          <%= t('virtus-content-p1') %>
        </p>
        <p>
          <%= t('virtus-content-p2') %>
        </p>
        <p>
          <%= t('virtus-content-p3').html_safe %>
        </p>
        <p>
          <%= t('virtus-content-p4') %>
        </p>
        <p style="font-weight: 600; font-style: italic">
          <%= t('virtus-content-p5').html_safe %>
        </p>

        <%= t('instructions-context').html_safe %>
        <br><br>
        <% if @spanish_document %>
        <div class="virtus" id="">
          <% if current_user %> 
          <%= link_to "Eliminar Bulletin Del Mes", virtu_path(@spanish_document), method: :delete, data: { confirm: 'Are you sure you want to delete spanish bulletin?' }, class: 'btn btn-danger m-2' %>
          <% end %> 
          <%= link_to "Click Aqui Para Ver Bulletin del Mes (Spanish)", rails_blob_path(@spanish_document.file), target: '_blank', class: 'btn btn-primary m-2' %>
        </div>
        <% else %>
        <div class="videos-heading text-center">
          <h2 id="videos-heading" class="">
            Bulletin (Espanol) no esta disponible....
          </h2>
          <% if current_user %> 
          <%= link_to t('nuevo-bulletin'), new_virtu_path, class: 'btn btn-primary m-2' %> <% end %>
        </div>
        <% end %>

        <% if @english_document %>
        <div class="virtus" id="">
          <% if current_user %> 
          <%= link_to "Delete Monthly Bulletin", virtu_path(@english_document), method: :delete, data: { confirm: 'Are you sure you want to delete english bulletin?' }, class: 'btn btn-danger m-2' %> 
          <% end %> 
          <%= link_to "Click Here To See Monthly Bulletin (English)", rails_blob_path(@english_document.file), target: '_blank', class: 'btn btn-primary m-2' %>
        </div>
        <% else %>
        <div class="videos-heading text-center">
          <h2 id="videos-heading" class="">
           Bulletin (English) not available...
          </h2>
          <% if current_user %> 
          <%= link_to t('nuevo-bulletin'), new_virtu_path, class: 'btn btn-primary m-2' %> <% end %>
        </div>
        <% end %>





      </div>
    </div>
  </div>
</section>

app/views/documents/new.html.erb
<section id="events" style="padding-bottom: 50px" class="text-center">
  <div class="events-heading">
    <h2 id="videos-heading" class="text-white"><%= t('new-document-heading') %></h2>
  </div>

  <!-- Form for English Document -->
  <%= form_with(model: @english_document, url: virtus_path, local: true, id: 'english-document-form') do |form| %>
  <div class="field">
    <%= form.label :file, class: "text-white"%>
    <%= form.file_field :file, class: 'btn btn-primary m-2'%>
  </div>

  <!-- Add a hidden field for the language -->
  <%= form.hidden_field :language, value: 'en' %>

  <!-- Submit Button -->
  <div class="actions">
    <%= form.submit 'Upload English Document', class: 'btn btn-primary m-2', id: 'add-english-button' %>
  </div>
<% end %>

<!-- Form for Spanish Document -->
<%= form_with(model: @spanish_document, url: virtus_path, local: true, id: 'spanish-document-form') do |form| %>
  <div class="field">
    <%= form.label :file, class: "text-white"%>
    <%= form.file_field :file, class: 'btn btn-primary m-2'%>
  </div>

  <!-- Add a hidden field for the language -->
  <%= form.hidden_field :language, value: 'es' %>

  <!-- Submit Button -->
  <div class="actions">
    <%= form.submit 'Upload Spanish Document', class: 'btn btn-primary m-2', id: 'add-spanish-button' %>
  </div>
<% end %>


</section>